version: '3.4'

services:
#Databases
  catalogdb:
    image: mongo

  shoppingcartdb:
    image: redis

  orderdb:
    image: postgres

#Microservices
  onlineshop.catalog.api:
    image: ${DOCKER_REGISTRY-}onlineshopcatalogapi
    build:
      context: .
      dockerfile: Services/OnlineShop/OnlineShop.Catalog.API/Dockerfile

  onlineshop.shoppingcart.api:
    image: ${DOCKER_REGISTRY-}onlineshopshoppingcartapi
    build:
      context: .
      dockerfile: Services/OnlineShop/OnlineShop.ShoppingCart.API/Dockerfile


  onlineshop.order.api:
    image: ${DOCKER_REGISTRY-}onlineshoporderapi
    build:
      context: .
      dockerfile: Services/OnlineShop/Order/OnlineShop.Order.API/Dockerfile

#Volumes
volumes:
  mongo_data:
  postgres_data:
