version: '3.4'

services:
#Databases
  catalogdb:
    image: mongo

  shoppingcartdb:
    image: redis

  orderdb:
    image: postgres

#Microservices
  onlineshop.catalog.api:
    image: ${DOCKER_REGISTRY-}onlineshopcatalogapi
    build:
      context: .
      dockerfile: Services/OnlineShop/Catalog/OnlineShop.Catalog.API/Dockerfile

  onlineshop.shoppingcart.api:
    image: ${DOCKER_REGISTRY-}onlineshopshoppingcartapi
    build:
      context: .
      dockerfile: Services/OnlineShop/ShoppingCart/OnlineShop.ShoppingCart.API/Dockerfile


  onlineshop.order.api:
    image: ${DOCKER_REGISTRY-}onlineshoporderapi
    build:
      context: .
      dockerfile: Services/OnlineShop/Order/OnlineShop.Order.API/Dockerfile

#Tools
  rabbitmq:
    image: rabbitmq:3.12-management-alpine

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile

#Others
volumes:
  mongo_data:
  order_data:

networks:
  default:


