version: '3.4'

services:
#Databases
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  shoppingcartdb:
    container_name: shoppingcartdb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OrderDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#Microservices
  onlineshop.catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__CatalogConnectionString=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=admin;Password=admin1234"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  onlineshop.shoppingcart.api:
    container_name: shoppingcart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=shoppingcartdb:6379"
    depends_on:
      - shoppingcartdb
    ports:
      - "8001:80"

  onlineshop.order.api:
    container_name: order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderConnectionString=Server=orderdb;Port=5432;Database=OrderDb;User Id=admin;Password=admin1234"
    depends_on:
      - orderdb
    ports:
      - "8002:80"


