version: '3.4'

services:
#Databases
  catalogdb:
    container_name: catalogdb
    restart: always
    environment:
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  shoppingcartdb:
    container_name: shoppingcartdb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=OrderDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

#Microservices
  onlineshop.catalog.api:
    container_name: onlineshop.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  onlineshop.shoppingcart.api:
    container_name: onlineshop.shoppingcart.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=shoppingcartdb:6379"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - shoppingcartdb
      - rabbitmq
    ports:
      - "8001:80"

  onlineshop.order.api:
    container_name: onlineshop.order.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__OrderConnectionString=Server=orderdb;Port=5432;Database=OrderDb;User Id=admin;Password=admin1234"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8002:80"

#Tools
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - onlineshop.catalog.api
      - onlineshop.shoppingcart.api
      - onlineshop.order.api
    ports:
      - "8100:80"

