name: .NET Microservices

env:
  SOLUTION_FILE: domino-app.sln

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: List Projects in Solution
      run: |
        # List the projects in the solution and capture the list in a variable
        projects=($(dotnet sln $SOLUTION_FILE list))
        echo "Projects in solution: ${projects[@]}"
      shell: bash

    - name: Build and Test Microservices
      run: |
        for project in "${projects[@]}"; do
          echo "Building and testing $project"
          dotnet build "$project" --no-restore
          dotnet test "$project" --no-build --verbosity normal
        done
      shell: bash
