name: Docker Compose for Local Testing

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Build and run Docker Compose
      run: docker-compose -f docker-compose.dev.yml up -d
